{% set name = "pidgen2" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pidgen2-{{ version }}.tar.gz
  sha256: 19ab99a5c116352aacb1d78930d79c2b7fe77adbdbbd03f8f0b88d7db03e491c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - jax
    - matplotlib-base
    - numpy
    - pandas
    - python >=3.6
    - scipy
    - uproot3
    - uproot >=4
    - xrootd >=5.2

test:
  imports:
    - pidgen2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.cern.ch/lhcb-rta/pidgen2
  summary: Tools for particle identification (PID) correction for LHCb detector
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
