{% set name = "pidgen2" %}
{% set version = "0.3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pidgen2-{{ version }}.tar.gz
  sha256: aec251421e84e402e25ca06d384ea6cc996a97d05ea09b6820e8e666cdf8a87c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.7
    - numpy
    - scipy
    - pandas
    - matplotlib-base
    - jax >=0.4
    - uproot <5.2
    - xrootd >=5.2

test:
  imports:
    - pidgen2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.cern.ch/lhcb-rta/pidgen2
  summary: Tools for particle identification (PID) correction for LHCb detector
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
