{% set name = "pidgen2" %}
{% set version = "0.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pidgen2-{{ version }}.tar.gz
  sha256: 97b233d8b2ee00936c33143dedb165036c2faee110259c2c80db3e635c635ca9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - pandas
    - matplotlib-base
    - jax
    - uproot <5,>=4.2
    - xrootd >=5.2

test:
  imports:
    - pidgen2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.cern.ch/lhcb-rta/pidgen2
  summary: Tools for particle identification (PID) correction for LHCb detector
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
